### ISSUE TITLE
Remote weather34-weewx issue

### ISSUE THREAD

**Issue by Damien0505** [taylormia/guides#1]
Hi,
Please forgive me if this is not the correct way to get towards a resolution for my issue, unfortunately I know no other.
I have followed your taylormia_remote_server_setup.pdf as hosted in Ian Steeple's weather34-Home-Weatherstation-Template-WeeWX-adapted.
I have finally got around to trying to get it working 100% and while I now have it displaying charts, they are appearing with "invalid date" and crazy data values (e.g temperatures of 60,000°C....  I know it gets hot here in Australia, but that is just a bit hot for my liking!)  :)

If you have a moment, would you be able to have a quick peek at my site, and see if there is anything obvious that may be causing the issue?  The URL is [https://weather.damienbeeby.com/]

The chartweewx files should be accessible via the web server too.  I have had a look at them and they appear correct; based on that I am wondering if it may be an issue due to the date formatting, sadly, my php skills are very poor.

It has me ripping out my hair, and considering I don't have any, that is no mean feat!  
![w34tempchart](https://user-images.githubusercontent.com/10883881/48669933-cdfc8180-eb62-11e8-93ae-94f78025a759.PNG)

I am happy to provide any config/files for your reference.

OS: Centos7
Nginx 1.14.1
PHP 5.6.38

Kind regards,
Damien

**Comment by taylormia** [comment]
Hi, I haven't been getting notifications from this page which is the reason I'm responding to you 19 days later. Also, am really pressed for time now..so will not be able to troubleshoot this in depth. On the surface I notice you are using PHP 5.6. I believe the latest templates require PHP 7.x. Have you tried upgrading to this version? I suggest posting this issue on the WXForum thread about this template: https://www.wxforum.net/index.php?topic=35231.0 or emailing the author of the template at steepleian@gmail.com. Good luck!

**Comment by Damien0505** [comment]
Apologies, I had forgotten all about this.  Ended up getting it sorted in the early hours of the morning, I wish I could remember what I did, but that was some weeks ago.
Many thanks for your reply!  :)
